### ISSUE TITLE
Create ReadMe and contributing guidelines

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#1]
This readme should be descriptive of what DEI Badging is and what the use of this website is.

**Comment by kaxada** [comment]
@adeyinkaoresanya here is an issue for you

**Comment by oma131** [comment]
@kaxada can I be assigned this issues

**Comment by kaxada** [comment]
This was handled in 2b67214b6969ef665b67b28ad0add2874ad90c70 unless there are future improvements and details missed
