### ISSUE TITLE
Revamp Footer

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#103]
Create separate commits for the following changes:

1. Change the styling of the header so that the content in the `community` and the `join us` section doesn't have the `showless`/`show more` options at the end
2. Change the `CHAOSS Community` words in the copyright section to a link to `https://chaoss.community`
3. Under the `Quick Links` Section, point the `FAQs` to `FAQ section` in the `home page`
4. Add another `Project Badging` Quick link to point to `https://badging.allinopensource.org` 
5. Correct the logo on the top left of the footer to look similar [to this](https://github.com/badging/badging/blob/main/src/assets/images/logos/chaoss-badging-logo.png)
6. Properly center the content so that it doesn't look different on the different screen sizes
7. Remove the `DEI logo` at the bottom of the socials

![image](https://user-images.githubusercontent.com/54111299/235857418-bca91e1c-be0c-4544-a691-199d1deaba4f.png)

**Comment by ibimina** [comment]
Can I work on this?

**Comment by SainiAditya1** [comment]
@kaxada , I would love to work on this?

**Comment by kaxada** [comment]
@SainiAditya1 let @ibimina work on this since she requested for it first. I am creating more issues

**Comment by ibimina** [comment]
@kaxada I had this error after creating a new branch and making a commit, was there any change made?
<img width="521" alt="error update" src="https://user-images.githubusercontent.com/96787210/236419079-2765a12f-5aca-4f50-9cca-188bc4c6133e.png">

**Comment by kaxada** [comment]
Hello @ibimina did you resolve this? It is related to linting and it directs you to where the error is. If you want to get more context of the error you can search what it means over the internet

**Comment by ibimina** [comment]
@kaxada I will run through again

**Comment by Shubhankar-1** [comment]
Has the issue been resolved?

**Comment by daluclemas** [comment]
hi @kaxada  , if this issue is availabe, i would like to be assigned the task

**Comment by cyrilossai** [comment]
hello have this issue been resolved? if yes

I would like to know how ?
