### ISSUE TITLE
Redesign Badged Events section

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#104]
Change this under the https://badging.chaoss.community/badged-events
![image](https://user-images.githubusercontent.com/54111299/235861297-9847d546-5106-4e6b-8a55-ffcf050c2226.png)

to this:
![image](https://user-images.githubusercontent.com/54111299/235861404-64274027-6909-4624-b45a-feadcc0c6203.png)

**Comment by Sky-De** [comment]
Hi there
Please assign this to me

**Comment by kaxada** [comment]
There you go @Sky-De. Please create a Draft Pull Request as soon as you make the first commit so that we can have progressive review

**Comment by Sky-De** [comment]
i finished it 
but when i try to commit something happens which im not familiar with
can you help me about this?
![fd](https://user-images.githubusercontent.com/79264045/236017055-93ddea3d-2365-4821-bc6f-3b30f1dddfdf.png)


inform me about anything which i can do to fix it


i spent couple of hours on it
it's result:
![desktopHover](https://user-images.githubusercontent.com/79264045/236017363-69a6f056-7c73-4d2a-92f4-5818603c95fd.png)

**Comment by kaxada** [comment]
hello, @Sky-De  this looks awesome. I am not sure why the linting is failing. could you try running `npm run format` independently without first committing so that you see what errors are there?
