### ISSUE TITLE
Mobile responsiveness for the landing page

### ISSUE THREAD

**Issue by daluclemas** [badging/eventBadging#109]
HI @kaxada , @Ruth-ikegah @iamkingsleey ,i'll like to work on making the landing page responsive if the design exists. if not and u want me to continue, i can do that as well

**Comment by tayyab-ilyas** [comment]
anyone working on this? if not I'd like to

**Comment by daluclemas** [comment]
> anyone working on this? if not I'd like to

Hi, i am

**Comment by Barry-dE** [comment]
I'd love to join you guys to work on it  as well

**Comment by kaxada** [comment]
duplicate of https://github.com/badging/badging/issues/80
