### ISSUE TITLE
Add mobile UI to the figma design

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#11]
so far the design that we have in [this Figma file](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website) is only for the desktop version. We shall need to guide the devs on how the mobile version will look like. This should be done ASAP

**Comment by maebasmrt** [comment]
Can you assign this to me? @Ruth-ikegah

**Comment by Ruth-ikegah** [comment]
sure @maebasmrt ! Assigned to you now

**Comment by maebasmrt** [comment]
@Ruth-ikegah I don't have access to the figma file

**Comment by Ruth-ikegah** [comment]
@iamkingsleey could you give @maebasmrt access to the file?

**Comment by iamkingsleey** [comment]
I need your email @maebasmrt

**Comment by maebasmrt** [comment]
maebasmart@gmail.com @iamkingsleey

**Comment by shreeram0k** [comment]
Hi @iamkingsleey 
can I contribute to this?

**Comment by smritiwaiba** [comment]
can i also help making the mobile UI please?

**Comment by iamkingsleey** [comment]
Yes you can @smritiwaiba

**Comment by iamkingsleey** [comment]
Thank you for indicating interest to contribute to the CHAOSS project.
I will request you join our CHAOSS Slack Community https://join.slack.com/t/chaoss-workspace/shared_invite/zt-1hn12x3wk-jabIzNEtPsskAVPeBohrNg and Send DM me on slack My User name is @Kingsley Mkpandiok.

I will be able to share details about the project and meeting links with you.

@shreeram0k 
@smritiwaiba

**Comment by Maryblessing** [comment]
Hello @iamkingsleey, is this issue completed now?

**Comment by kaxada** [comment]
mobile screens can be found at this [link](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?type=design&node-id=1289%3A2903&mode=design&t=JJOdPIdSY3cXAQGZ-1)
