### ISSUE TITLE
Graphic needed: CHAOSS Retractable Banner

### ISSUE THREAD

**Issue by ElizabethN** [badging/eventBadging#114]
Hi Design Team 😍 

We are going to be hosting our first booth at open source conferences this year and we need some signage. In particular, we are looking at getting [this retractable banner printed](https://www.vistaprint.com/signs-posters/retractable-banners) (in the 33"x81" size). 

Is there anyone that would be interested in designing a generic "CHAOSS" banner that would have the CHAOSS logo and basic design elements of our slide deck and website? 

If so, here's a PDF template (I also have an .ai file too). 
[pdf-template.pdf](https://github.com/badging/badging/files/11804898/pdf-template.pdf)

We are looking to have this ready to go to the printer by **June 30, 2023.** 

Thank you!  :heart:

**Comment by kaxada** [comment]
@ElizabethN do you think there are more branding materials we may need apart from the banner? @iamkingsleey will be good in leading this team

**Comment by ElizabethN** [comment]
@kaxada Maybe a tablecloth in the future but that would just have the CHAOSS logo on it. @iamkingsleey advised me to open an issue but I couldn't quite remember where the best place would be - if there's a better repo let's move it there :smile:

**Comment by kaxada** [comment]
Good thing is tagged. We can collaborate here if we get a better place we can shift the conversation.

**Comment by iamkingsleey** [comment]
It's okay, @ElizabethN. We'll get a few hands to deliver this before the deadline. Meanwhile, are there specific details you would like to include on each of these banners/decks? For CHAOSScon, we added sponsors, QR code, and the event hashtag.
![Roll-up-Update-II-01](https://github.com/badging/badging/assets/63562509/d13ddfb0-b158-4756-9c5b-2246d8c6ce28)
![Banner-Design-01](https://github.com/badging/badging/assets/63562509/47da2803-156c-4d92-8a9a-3352c4cf5ccc)

**Comment by ElizabethN** [comment]
@iamkingsleey thank you so much! Nah, this would be just a generic banner we could use at any CHAOSS event, with mostly the CHAOSS logo. I do like the idea of a QR code that would lead to the CHAOSS website, though! I also like some of the design backgrounds and elements in the website and [slide deck](https://docs.google.com/presentation/d/1issLzBwMoVJybKFpB4hXR-DTdZ0SHVYADPkRSlhc1-I/edit#slide=id.g1385ab96aac_1_26).

**Comment by iamkingsleey** [comment]
Okay.

**Comment by iamkingsleey** [comment]
What do you think @ElizabethN? I am available to make any updates 
![002](https://github.com/badging/badging/assets/63562509/e9fbef5b-308f-42b1-9121-014f373b76eb)
![001](https://github.com/badging/badging/assets/63562509/7ec9f06a-66a2-47ed-81dd-8624eb60a6cd)

**Comment by ElizabethN** [comment]
@iamkingsleey ohhhhhh I love these so much! My only suggestion would be to maybe move the teal CHAOSS band closer to the top, since this will be behind a table in a booth and there might be chairs blocking it. I think I like the teal a little more than the pink, personally.

@germonprez what do you think about it?

**Comment by iamkingsleey** [comment]
Noted, Yeah I love the teal too @ElizabethN

**Comment by germonprez** [comment]
Love them!! Love the teal too.

**Comment by iamkingsleey** [comment]
If this works then, below is a editable/printable pdf of the design. @ElizabethN 
![Mockup](https://github.com/badging/badging/assets/63562509/ecf33169-52e2-4d05-81ba-b243b9631622)
[CHAOSS-Banner-Design.pdf](https://github.com/badging/badging/files/11875300/CHAOSS-Banner-Design.pdf)

**Comment by ElizabethN** [comment]
@iamkingsleey THIS IS WONDERFUL! Thank you so, so much for this. I'll let you know if I need anything else for this, but this PDF should work great. 🥳 😻

**Comment by iamkingsleey** [comment]
Anytime 👌
