### ISSUE TITLE
Create Header Component

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#2]
![Image](https://user-images.githubusercontent.com/54111299/193425523-cfa56655-23e4-4524-83da-0a557f9470d1.png)

**Comment by dotun2203** [comment]
Good morning, i will like to take this up. i don't mind you assigning me

**Comment by kaxada** [comment]
@dotun2203 it is fine. what we basically need is to have a reusable header that looks like those. I have already created an assets folder with the necessary colour and logos you may need. We are still having a discussion about Mobile responsive but you can start with the desktop version. let me know when you are stuck or in dilemma

**Comment by dotun2203** [comment]
No problem

**Comment by kaxada** [comment]
@dotun2203 consider using `react-router-dom` for all the links in the header

**Comment by dotun2203** [comment]
hello 
 currently trying to work on the header component, but it's not displaying right on the repo i cloned. I created another react app and copy and paste the same code, and it worked

**Comment by dotun2203** [comment]
> hello currently trying to work on the header component, but it's not displaying right on the repo i cloned. I created another react app and copy and paste the same code, and it worked

is it possible there's something i am not doing right as regards the repo?

**Comment by dotun2203** [comment]
@kaxada

**Comment by kaxada** [comment]
@dotun2203 are you still available for this contribution?

**Comment by dotun2203** [comment]
> @dotun2203 are you still available for this contribution?

Yes, I am still available,  I had some issues sometimes ago,  I tagged you on the group but I guess you were busy. 

I saw you made some changes on the repo, I'll update my own and see if I am still getting the error

**Comment by kaxada** [comment]
@dotun2203 actually someone sent in  PR https://github.com/badging/badging-website/pull/51 addressing this. So I'll close it. But we are creating more issues because the site still needs to be polished.
