### ISSUE TITLE
Footer and Nav Component for Mobile Website

### ISSUE THREAD

**Issue by iamkingsleey** [badging/eventBadging#23]
Footer and Nav Component Design by Shalom

Deadline: 14th of October

**Comment by activus-d** [comment]
Hello @iamkingsleey is the design for this ready? I would like to work on this.

**Comment by Delight362** [comment]
In progress

**Comment by iamkingsleey** [comment]
Thank you @Delight362. @activus-d we have a few pending tasks, But that will commence once the components are ready.

**Comment by ShalomOhuegbe** [comment]
@iamkingsleey i am done with my task. Expecting a review soon, thanks

**Comment by LamiWilliams** [comment]
@ShalomOhuegbe I just did a review as well as an iteration suggestion on Figma. Please, check

**Comment by Maryblessing** [comment]
@LamiWilliams @iamkingsleey if this issue is completed, can we please close it up?

**Comment by LamiWilliams** [comment]
Hi @Maryblessing This has been completed and can be closed. Thanks!

**Comment by Maryblessing** [comment]
Thank you @LamiWilliams 
@kaxada please help close this issue
