### ISSUE TITLE
Mobile website: Badged Events page design

### ISSUE THREAD

**Issue by iamkingsleey** [badging/eventBadging#25]

**Comment by LamiWilliams** [comment]
@iamkingsleey @Primack worked on this

**Comment by LamiWilliams** [comment]
I'm joining him too. Please, review my iterations @Primack

**Comment by Maryblessing** [comment]
Hello @LamiWilliams how is this coming along? Is this issue completed now?

**Comment by kaxada** [comment]
Yes it was but I created a new one for it to redesign it -> https://github.com/badging/badging/issues/104
