### ISSUE TITLE
Youtube Banner and Thumbnail design.

### ISSUE THREAD

**Issue by iamkingsleey** [badging/eventBadging#27]
The timeline for this is Friday 14th of October

**Comment by iamkingsleey** [comment]
@oma131 issue raised by Elizabeth

**Comment by ShalomOhuegbe** [comment]
@iamkingsleey I do not have details for designing the thumbnail such as images and the headline topic for the youtube video please

**Comment by iamkingsleey** [comment]
Hi Elizabeth you can review the youtube thumbnail designs @ElizabethN T @oma131 https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=1126%3A3399 
Let me know your feedback.

**Comment by ElizabethN** [comment]
These look awesome, and I love where this is going! A few quick edits:
-  we *just* changed the Value working group to the OSPO Working Group, so this one will need to be updated. Sorry about that! :smile:
- Could we also get ones for
  - Weekly Community Meetings
  - CHAOSS Africa
  - CHAOSS Asia-Pacific
  - Web Content
  - App Ecosystem 
  - Hackathons

Again, these are not urgent; just whenever you all have time. These are so wonderful! 

![thankyou](https://user-images.githubusercontent.com/57594/195868916-fe0176ff-53d7-4d1c-a3c9-84ebc5f2cdf9.gif)

**Comment by oma131** [comment]
These are really beautiful😍😍😍😍
Thank you guys so much for working on this so fast, the work speed is amazing!!!

**Comment by lemostrash** [comment]
hello, can I still participate by making the banner and thumbnail?

**Comment by iamkingsleey** [comment]
> These look awesome, and I love where this is going! A few quick edits:
> 
> * we _just_ changed the Value working group to the OSPO Working Group, so this one will need to be updated. Sorry about that! 😄
> * Could we also get ones for
>   
>   * Weekly Community Meetings
>   * CHAOSS Africa
>   * CHAOSS Asia-Pacific
>   * Web Content
>   * App Ecosystem
>   * Hackathons
> 
> Again, these are not urgent; just whenever you all have time. These are so wonderful!
> 
> ![thankyou](https://user-images.githubusercontent.com/57594/195868916-fe0176ff-53d7-4d1c-a3c9-84ebc5f2cdf9.gif) [ ![thankyou](https://user-images.githubusercontent.com/57594/195868916-fe0176ff-53d7-4d1c-a3c9-84ebc5f2cdf9.gif) ](https://user-images.githubusercontent.com/57594/195868916-fe0176ff-53d7-4d1c-a3c9-84ebc5f2cdf9.gif) [ ](https://user-images.githubusercontent.com/57594/195868916-fe0176ff-53d7-4d1c-a3c9-84ebc5f2cdf9.gif)

Thank you @ElizabethN. Feedback is noted

**Comment by iamkingsleey** [comment]
Thank you @ElizabethN and @oma131.
Have taken note of the feedback

**Comment by iamkingsleey** [comment]
@lemostrash are you on our slack community?

**Comment by lemostrash** [comment]
@iamkingsleey I'm a newbie looking for a pull request with my experience level

**Comment by Speeddesign1** [comment]
Im just joining the design team here @iamkingsleey
