### ISSUE TITLE
Mobile website: About us and Landing page design

### ISSUE THREAD

**Issue by iamkingsleey** [badging/eventBadging#28]
This is handled by Toria.

**Comment by Anita-ihuman** [comment]
@iamkingsleey please can you add more context to the issue description.?

**Comment by Maryblessing** [comment]
Hi @iamkingsleey, is this still a valid issue? If yes, can you please provide more context to it? Looks like @Anita-ihuman wants to work on this? Thank you

**Comment by TemitopeAsama** [comment]
Hi @iamkingsleey, if this is still open. I'd love to take it on.

**Comment by iamkingsleey** [comment]
These designs have been handled. However, my concern that has stalled the implementation of the "About us" mobile design is the user experience. I will take a look at it again. @Maryblessing

**Comment by Maryblessing** [comment]
Alright. Thanks @iamkingsleey.
