### ISSUE TITLE
Create Footer Component

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#3]
consider using `react-router-dom` for all the links in the footer
![Image](https://user-images.githubusercontent.com/54111299/193452427-fb8c1687-7693-435a-bd8f-76ae6cc2446b.png)

**Comment by misspee007** [comment]
To be clear, do you mean using \<Link> instead of \<a> ?

**Comment by kaxada** [comment]
Yes we are using `Link` from `react-router-dom` I meant that we have `links` in the footer like the `about us`, `event badging`, `contact us`, `project badging` etc. we are using the `react-router-dom` package to link these pages. This is for scalability purposes since we are using react

**Comment by audreymengue** [comment]
Hey @kaxada , can I work on this?

**Comment by kaxada** [comment]
Yes sure. Let me know when you need help

**Comment by audreymengue** [comment]
Hi @kaxada, if I understand very well, the static files have to be served form express in a folder called build? I believe the "build" folder will be created when we push to prod.

**Comment by kaxada** [comment]
When you clone the repo, supply a `port` number in a `.env` file and then run `npm run dev` in the terminal 

The build folder is generated with the `build scripts` for production purposes.

I think I'll come up with a small `ReadME.md` that guides contribution in the meantime

**Comment by audreymengue** [comment]
@kaxada can the branch bear the name of the issue?

**Comment by kaxada** [comment]
For now there are no naming conventions as far branches are concerned. Anything should work as long as it is short and meaningful.

**Comment by audreymengue** [comment]
Hey @kaxada I have an error bothering me lately and I was wondering if I could use your help.

Here in Footer.js

`import React from "react";
import { NavLink } from "react-router-dom";
import "../../assets/styles/variables.scss"


const Footer = () => {
    return <h2>
        <NavLink> Hello links</NavLink>
    </h2>;
};

export default Footer;
`

Here is where I am styling the background to text scss, the file is variables.scss in the assets folder

`$primary-color: #46BA8A;
$secondary-color: #D61B5E;
$background-color: #F5F5F5;
$primary-container-color: #AFFFEC;
$secondary-container-color: #FFE7EF;

h2 {
    background-color: $background-color;
}`

Here is the error I am facing when running the app in my terminal and browser.
![03102022](https://user-images.githubusercontent.com/51542962/193630045-2f1bf21b-415d-4f16-bc5c-238cd14bfcf9.png)

**Comment by kaxada** [comment]
@audreymengue please pull the changes in the main branch. they address that issue

**Comment by audreymengue** [comment]
Alright. Thank you @kaxada

**Comment by audreymengue** [comment]
@kaxada here is how far I have come with the footer as far as the desktop view is concerned.

But, is it possible to have more specs in terms of the fonts I need to use, colors etc... on particular sections/header, so I can wrap up with it?

Also, I cannot get colorful icons because I am using the free version.

And the CHAOSS logo does not show and I cannot figure out why.

Thanks.


![Screenshot (139)](https://user-images.githubusercontent.com/51542962/194115427-5e189d41-15af-47a4-b9a1-2c41b90ecc0d.png)

**Comment by Delight362** [comment]
![Image](https://user-images.githubusercontent.com/96892410/194340470-02ec4c2d-9a88-4c95-bd5d-dc609ec5c8a7.png)
I made this out using HTML and CSS, hope it can be helpful .

**Comment by oma131** [comment]
@audreymengue you have done beautiful work so far, Here is a[ link to the Figma file](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website) to get more specifications in terms of font size, font color etc.

**Comment by audreymengue** [comment]
Thank you @oma131. Thanks for the Figma file.

**Comment by audreymengue** [comment]
![Screenshot (140)](https://user-images.githubusercontent.com/51542962/196573337-d721ebf3-ca7a-493d-82cd-eda3fccf0159.png)

@kaxada  and @oma131  for some reasons I am unable to use the svg. Please if you have a trick on how to use these svgs, let me know. In the mean time, I am using common image files like jpeg, png. Also working on the DEI badging. Thanks for your feedback in advance.

**Comment by Denike-d** [comment]
Hello @kaxada 
Is this Issue still opened?

**Comment by kaxada** [comment]
@Denike-d this is going to be reopened as soon as we merge this PR https://github.com/badging/badging-website/pull/53

**Comment by kaxada** [comment]
This issue has been closed since it was partly addressed in https://github.com/badging/badging-website/pull/55 . I am opening up a new issue that addresses the current footer
