### ISSUE TITLE
Update Hosting from Heroku to Vercel

### ISSUE THREAD

**Issue by Ruth-ikegah** [badging/eventBadging#46]
Heroku recently stopped their free plan so we have to move our hosting to Vercel

**Comment by Teek-tech** [comment]
Okay, I will jump on it!

**Comment by Ruth-ikegah** [comment]
Thanks @Teek-tech assigned to you now!

**Comment by germonprez** [comment]
I am going to approve the integration request for Vercel

**Comment by Ruth-ikegah** [comment]
yes thanks @germonprez

**Comment by Teek-tech** [comment]
We can close this issue now I guess? @Ruth-ikegah
