### ISSUE TITLE
added basic routing structure

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#5]

**Comment by NnajiChimuanya** [comment]
Can I  get assigned this?

**Comment by kaxada** [comment]
Hey @NnajiChimuanya , I think we can hold on to implement this. I created it but I have a feeling it may be implemented under #3 or #2 since they have a lot of general links. but I am still looking through the general structure of the pages and will let you know. 

Have you tried going through some issues under [this board](https://github.com/orgs/badging/projects/4)?

Alternatively, you can check out other open issues for now in the repo.

**Comment by kaxada** [comment]
Partly tackled in https://github.com/badging/badging-website/pull/55 and will continue evolving so I am closing it
