### ISSUE TITLE
Graphic for 100th Badge Needed

### ISSUE THREAD

**Issue by ElizabethN** [badging/eventBadging#52]
Hi! We are almost at the 100th badge awarded, so it would be great if this is something we can highlight on our blog and twitter. Would it be possible to get a graphic of some kind to help us celebrate 100 badges awarded? THANK YOU!!

**Comment by iamkingsleey** [comment]
Noted @ElizabethN and @kaxada

**Comment by Delight362** [comment]
Have this been handled

**Comment by iamkingsleey** [comment]
Not yet @Delight362.

**Comment by Delight362** [comment]
Okay

**Comment by Delight362** [comment]
@iamkingsleey check out this design I made for this issues :
https://docs.google.com/document/d/1WkS_DzlMTZBGetXI_qkD0NPwBg5YZ4T9N3pKdFwKtfc/edit?usp=drivesdk

**Comment by iamkingsleey** [comment]
Nice work @Delight362, Thank you for the creative idea behind this. However, since it's a badge; creating something around this concept would make it much more relatable. Secondly, we must ensure it resonates with the CHAOSS brand style. This can help [Figma](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=2059%3A5286&t=YIETPw1egdsG4sVL-0)

**Comment by Delight362** [comment]
Okay got it

**Comment by Delight362** [comment]
@iamkingsleey  please check the update https://docs.google.com/document/d/1WkS_DzlMTZBGetXI_qkD0NPwBg5YZ4T9N3pKdFwKtfc/edit?usp=drivesdk

**Comment by iamkingsleey** [comment]
Thank you so much @Delight362. Innovative, A few additions to the template I shared. I decided to work with your idea but make a couple of changes that resonate more with the CHAOSS brand style.  what do you think @ElizabethN? @Delight362 and I worked on this
![100th Badge](https://user-images.githubusercontent.com/63562509/220309035-2014d62c-2083-4716-a07e-639ff24d03b3.jpg)

**Comment by kaxada** [comment]
This looks awesome. Just a little tweaking with the grammar. If you're planning to make it better no problem. But it already suffices 

Either you wanted to mean `100 badges awarded` or `100th badge awarded`

**Comment by iamkingsleey** [comment]
Any suggestions? @Delight362

**Comment by iamkingsleey** [comment]
Thank you @kaxada

**Comment by iamkingsleey** [comment]
![Event Badge](https://user-images.githubusercontent.com/63562509/220316479-fc6ed22d-e996-4cf7-b4fb-960f474d4a36.jpg)

**Comment by kaxada** [comment]
@ElizabethN will give her submission but this looks cute

**Comment by Maryblessing** [comment]
> ![Event Badge](https://user-images.githubusercontent.com/63562509/220316479-fc6ed22d-e996-4cf7-b4fb-960f474d4a36.jpg)

Love it!

**Comment by iamkingsleey** [comment]
So @Ruth-ikegah suggested we use CHAOSS DEI badging logo and suggested a better write-up too
![DEI Badging](https://user-images.githubusercontent.com/63562509/220942513-0dd647fd-4818-452d-b868-0ecfe77f11bd.jpg)

**Comment by kaxada** [comment]
Ohh cool. I didn't know we already have one. Let's actually replace this logo with the CHAOSS logo on the badging website

**Comment by Maryblessing** [comment]
> So @Ruth-ikegah suggested we use CHAOSS DEI badging logo and suggested a better write-up too ![DEI Badging](https://user-images.githubusercontent.com/63562509/220942513-0dd647fd-4818-452d-b868-0ecfe77f11bd.jpg)

This is great. 

I was thinking in the lines of "100 DEI badges awarded to Events" then the other text follows. I feel like people already know it's been awarded by us, CHAOSS.

**Comment by ElizabethN** [comment]
Loving these comments and feedback! I might just add maybe we should tighten up the graphic, because there seems to be a lot of extra space now. But I'm no designer, so I trust your judgment!

**Comment by Delight362** [comment]
Okay let's see what we can come up with.

**Comment by iamkingsleey** [comment]
You sound like a designer already @ElizabethN ...Lol. Will work with @Delight362 to get that fixed

**Comment by Maryblessing** [comment]
We've agreed on the text right? @iamkingsleey

**Comment by iamkingsleey** [comment]
Yes @Maryblessing

**Comment by Maryblessing** [comment]
Cool

**Comment by iamkingsleey** [comment]
![DEI Badging_](https://user-images.githubusercontent.com/63562509/221598624-e2384aec-4de2-43ad-a4b3-b7b7379bdd59.jpg)
Some balloons to celebrate and make it more colorful ...Lol and Less white space now in the design. What do you think @ElizabethN?

**Comment by Delight362** [comment]
This looks awesome, @iamkingsleey

**Comment by Maryblessing** [comment]
Hi @iamkingsleey @kaxada, you think it would be a great idea to have the badge count on the website? Like a section that counts down/up to how many badges we've awarded. Do you understand?

**Comment by kaxada** [comment]
I'll let @iamkingsleey decide on this one
