### ISSUE TITLE
Change background of Landing Page

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#57]
The [background on the current landing page](https://badging-website.netlify.app/) as of commit 0c8420dd0469f292f17aafc1317f65709c4c96fb is not the same as that of the [Figma Design](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=1289%3A2903&t=njpDMYfbokNwYaHG-0).

Redesign the background of the landing page to look like that of the Figma Design

**Comment by ahmad-shoja** [comment]
I'm going to change background color

**Comment by kaxada** [comment]
Alright. I'll assign this to you. Make sure you push changes frequently for easy review
