### ISSUE TITLE
Implement the `About us` Page

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#59]
Design the `about us` page with proper routing.
* All assets are in the `src/assets` folder. If an asset is missing, consider adding it to only the `asset` folder with proper naming. 
* Do not include the `Submit your Event for a DEI Badge` section (the one above the footer in the about section) because that is going to be a component of its own.

For now, use all the content that is there but soon some content will be changed and you should not worry about that and exclude the `Motivation to Apply` section since it will be a component of its own (refer to https://github.com/badging/badging-website/issues/61)

**Comment by davidadediji** [comment]
@kaxada can I pick up this issue

**Comment by kaxada** [comment]
Yes please @davidadediji. I'll assign it to you. Make sure you create a draft PR and push small changes for easy review
