### ISSUE TITLE
Create landing Page

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#6]

**Comment by NnajiChimuanya** [comment]
is there an already made design for the landing page?
if yes, you can assign it to me

**Comment by kaxada** [comment]
Yes, @NnajiChimuanya, there is. Please [check out this Figma file.](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=243%3A994)

**Comment by NnajiChimuanya** [comment]
Do I have to worry about making it mobile responsive, there is no design for mobile
