### ISSUE TITLE
 Implement the `Submit your Event for a DEI Badge` section

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#60]
Refer to this [Figma Design](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=243%3A994&t=njpDMYfbokNwYaHG-0) for more Details 

![image](https://user-images.githubusercontent.com/54111299/207666854-17ceee54-dbee-4185-a49f-fbf9397a29df.png)

**Comment by Denike-d** [comment]
Hello @kaxada assign this to me

**Comment by kaxada** [comment]
@Denike-d there you go. Waiting for your contribution

**Comment by Denike-d** [comment]
Hello @kaxada I haven't been able to run the project on my end. I updated my Node.js but still not able to run it, instead I'm seeing "website running on Port: undefined". Would appreciate if you can help me sort this.

**Comment by kaxada** [comment]
Hello @Denike-d Have you sorted this out? Please consider using `npm run dev` instead of `npm run start`

**Comment by kaxada** [comment]
@Denike-d are you still working on this issue? Do you have any updates?

**Comment by Denike-d** [comment]
@kaxada Yes I'm still working on it. Sorry for the delay. I will push what I have done later in the day

**Comment by kaxada** [comment]
@Denike-d are you still working on this?

**Comment by daluclemas** [comment]
Hi @kaxada is this issue open, I'd like to work on it

**Comment by Maryblessing** [comment]
Hi @kaxada, can we assign this issue to @daluclemas? Thank you

**Comment by kaxada** [comment]
Hello, @daluclemas sorry for the late response. Please go on and work on the issue! thank you @Maryblessing for looking out

**Comment by daluclemas** [comment]
> Hello, @daluclemas sorry for the late response. Please go on and work on the issue! thank you @Maryblessing for looking out

hi @kaxada ,  thanks alot

**Comment by Maryblessing** [comment]
Hi @daluclemas, I'm just checking in with you

**Comment by daluclemas** [comment]
hi @Maryblessing , i am still working on it. created a pr for another issue though. Issue 91. requested assistance resolving conflicts.

**Comment by daluclemas** [comment]
hi @kaxada , i'd like a confirmation on this please. is the only enhancement making this a carousel? also , i noticed the background has lines, i can't seem to export that

**Comment by kaxada** [comment]
@daluclemas I don't think the carousel is necessary because we are not planning to add more logos. you can just make a hover animation or something to make it look beautiful. let me know when you can challenges we can set up a call

**Comment by daluclemas** [comment]
> @daluclemas I don't think the carousel is necessary because we are not planning to add more logos. you can just make a hover animation or something to make it look beautiful. let me know when you can challenges we can set up a call

alright @kaxada , i'll reach out if i encounter an issues

**Comment by daluclemas** [comment]
hi @kaxada  and @Maryblessing , may i be giving a little more time on this task. currently experiencing a personal blocker. i'll reach out on slack

**Comment by daluclemas** [comment]
hi @kaxada , i need assistance. would u be available for a call?

**Comment by Maryblessing** [comment]
> hi @kaxada and @Maryblessing , may i be giving a little more time on this task. currently experiencing a personal blocker. i'll reach out on slack

Hello @daluclemas, I hope you're good!
No worries

**Comment by daluclemas** [comment]
> > hi @kaxada and @Maryblessing , may i be giving a little more time on this task. currently experiencing a personal blocker. i'll reach out on slack
> 
> Hello @daluclemas, I hope you're good! No worries

hi @Maryblessing , yes i am better now. i do need assistance. i can't commit. idk why. it's throwing an error about lin-staged. i don't know if you or @kaxada would be available for a call. i need assistance
