### ISSUE TITLE
Implement the `Motivation to Apply`  component

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#61]
This component should be implemented with an 'HTML' table layout and responsive or scrollable
![image](https://user-images.githubusercontent.com/54111299/207671318-58467543-40e2-46df-9faa-240b4fbaf0dc.png)

**Comment by ASN011** [comment]
@kaxada  please assign this to me

**Comment by kaxada** [comment]
@Adityasaini10012001 there you go

**Comment by kaxada** [comment]
@Adityasaini10012001 are you still working on this issue or I should assign it to someone else?

**Comment by ASN011** [comment]
@kaxada I will complete it very soon

**Comment by kaxada** [comment]
Ok. That's great. You can push what you have e even if it's incomplete. It can be maintained as a draft PR

**Comment by Aarav238** [comment]
i  would like to work on it. @kaxada  Please assign this to me.

**Comment by ASN011** [comment]
@Aarav238 I am working on it and almost done it going to commit it tomorrow....

**Comment by Maryblessing** [comment]
Hi @linux1011, are you still working on this? Is there any blocker you're facing? Kindly let us know. If not, we're happy to reassign it to someone else.

**Comment by ibimina** [comment]
@Maryblessing can I work on this?

**Comment by kaxada** [comment]
Yes please @ibimina

**Comment by ibimina** [comment]
@kaxada I have tried to stage file changes and commit but keep getting this error, Is there a command I need to run before git commit?

<img width="745" alt="error" src="https://user-images.githubusercontent.com/96787210/235762687-be0ae206-d88e-4e90-a157-2bc769f4bc6a.png">

**Comment by kaxada** [comment]
@ibimina that setting was included so that you don't stage files that are having errors or not well formated. I don't use windows but I don't know what happens when you cancel the warning prompt

**Comment by ibimina** [comment]
@kaxada I tried using both the terminal and vs code windows, still got the same error 
I will try again

**Comment by kaxada** [comment]
When it fails you send me a slack
