### ISSUE TITLE
Add components to designs

### ISSUE THREAD

**Issue by iamkingsleey** [badging/eventBadging#69]
Ensure all designs made (Web or Mobile) are updated with available components.

**Comment by fiddyhamma** [comment]
Can you assign this task to me?

**Comment by iamkingsleey** [comment]
Done, Thank you @fiddyhamma

**Comment by Maryblessing** [comment]
Hi @fiddyhamma, how is this going? Please if you're done with this issue, kindly comment so we know. If not, could you please work on completing this in a week's time so we can close this up? Thank you

**Comment by fiddyhamma** [comment]
Hello @Maryblessing 
I've completed most parts of it but some texts require a new design system and i'm waiting on Ayomide to complete it.

**Comment by Maryblessing** [comment]
Hi @iamkingsleey, who is Ayomide and how can we reach them?

**Comment by adelanaofficial** [comment]
Hello @Maryblessing , I'm Ayomide:)

I worked with @fiddyhamma and thanks to her we've completed the task. I have tagged Lami on the Figma board. This issue will be closed soon.

**Comment by Maryblessing** [comment]
Thank you both!
@kaxada please help close this issue. Thanks
