### ISSUE TITLE
Design 404 page

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#7]

**Comment by Scentjuls** [comment]
Hello @kaxada can this be assigned to me?

**Comment by kaxada** [comment]
Yes sure. Look through the figma file and look at how the 404 page was designed. 

We may need to configure redirects that will fall under 404 later.

**Comment by meenarh** [comment]
Hi @kaxada  I wanted to ask if this issue has been fixed. If it's still open, I'd like to work on it.

**Comment by meenarh** [comment]
Hi @kaxada can I work on this?

**Comment by kaxada** [comment]
@meenarh I am pinging @iamkingsleey here to give you guidance on how to go forward

**Comment by meenarh** [comment]
Alright. Thank you. Hi @iamkingsleey 🙂

**Comment by meenarh** [comment]
@kaxada could you please point me to the Figma link? Thank you

**Comment by kaxada** [comment]
@meenarh here -> https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website

**Comment by meenarh** [comment]
Thank you @kaxada

**Comment by kaxada** [comment]
I think you can go on and design this @meenarh

**Comment by shubham21155102** [comment]
Hello @kaxada is this issue still open?
Can you assign it to me?

**Comment by kaxada** [comment]
@shubham21155102  I am not sure whether @meenarh is still working on this but you can go ahead and work on it.

**Comment by iamkingsleey** [comment]
Hello, @shubham21155102 Thank you for indicating interest to take on this task. Can you connect with us on slack to get the resources you need to pull this off? If yes, Here is the [link](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-1pooh7hk2-JzfJy4GQem0JtX0N6HhkOA)

**Comment by iamkingsleey** [comment]
Hi @shubham21155102 Apologies please, I just noticed there's a design for that already. [Figma ](https://www.figma.com/proto/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=2836%3A7074&scaling=contain&page-id=62%3A9). No worries, there are other design issues that need fixing. Let me know when you find another you would like to work on.

**Comment by shubham21155102** [comment]
Okay sir sure
