### ISSUE TITLE
Combine mobile and desktop elements into one components

### ISSUE THREAD

**Issue by iamkingsleey** [badging/eventBadging#70]
This is to ensure easy accessibility and use of the different components in the Figma workspace

**Comment by adelanaofficial** [comment]
Kindly assigne to this task.

**Comment by iamkingsleey** [comment]
Done @adelanaofficial

**Comment by adelanaofficial** [comment]
Thank you.

**Comment by LamiWilliams** [comment]
@adelanaofficial Well done on the work done so far! I have reviewed the mobile and desktop Roadmap sections (I created them separately like the nav bar, though). Used the "atoms" you created. Check out the prototypes of the [mobile](https://www.figma.com/proto/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=2667%3A6113&scaling=scale-down&page-id=2517%3A5846&starting-point-node-id=2667%3A6113&show-proto-sidebar=1) and [desktop](https://www.figma.com/proto/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=2668%3A7165&scaling=scale-down&page-id=2517%3A5846&starting-point-node-id=2668%3A7165&show-proto-sidebar=1) to get an idea of  how the flow looks. What do you think?

I'll let you know when I complete the mobile "Review Checklist" section tomorrow

**Comment by adelanaofficial** [comment]
Thank you @LamiWilliams, I'm happy to have helped. Your feedback is really appreciated! 
I will check the prototypes mentioned and will drop a comment if necessary!

Just in case, would there be any more edits?
Also, I could also help with the "Review Checklist" if needed.

**Comment by Maryblessing** [comment]
Hi @iamkingsleey, if this issue has been worked on, can we please close it? Thanks

**Comment by adelanaofficial** [comment]
Hey, @Maryblessing.

I have completed the issue. I'll mention it to @iamkingsleey so he can close it.

@iamkingsleey I have also updated the text styles too. :)
CC: @LamiWilliams

**Comment by Maryblessing** [comment]
Awesome! Thanks @adelanaofficial
