### ISSUE TITLE
The accordions are overlapping the footer when expanded

### ISSUE THREAD

**Issue by Vickyabiodun** [badging/eventBadging#77]
<img width="668" alt="Screenshot 2023-01-31 at 20 42 53" src="https://user-images.githubusercontent.com/86018345/215867694-b321873d-4da4-495c-babd-5766a7fea9a8.png">

**Comment by ibimina** [comment]
@Ruth-ikegah can I work on this Issue?

**Comment by olabimpe-lo** [comment]
@Teek-tech @kaxada Hi, can I work on this issue?

**Comment by Maryblessing** [comment]
Hi @olabimpe-lo, are you still available to work on this? If yes, let's assign this issue to them @kaxada @Ruth-ikegah.
Thanks

**Comment by ibimina** [comment]
@Maryblessing I am available incase she is not

**Comment by olabimpe-lo** [comment]
@Maryblessing Yes yes I am available to work on it, thank you.

**Comment by kaxada** [comment]
Hello @olabimpe-lo and @ibimina. Good to know that you want to work on this issue. I'll assign the issue to @ibimina since she made the request first.

**Comment by Maryblessing** [comment]
Hi @ibimina, thanks for your interest. We're placing a timeline for this issue and that's one week. I think we've spent 3 days already. KIndly let us know when you're done. Thanks
