### ISSUE TITLE
fix social links 

### ISSUE THREAD

**Issue by ASN011** [badging/eventBadging#78]
social links does not have complete information..

**Comment by CatherineKiiru** [comment]
Hi @Adityasaini10012001, could you give more details on the issue? I'd like to work on this

**Comment by ibimina** [comment]
@Ruth-ikegah  can I work on this

**Comment by Maryblessing** [comment]
Hi @Ruth-ikegah, can you please assign this issue to @ibimina? Thanks

**Comment by ibimina** [comment]
@Ruth-ikegah @Maryblessing  can I get the official links for Chaoss

**Comment by ibimina** [comment]
@kaxada can  get the official links

**Comment by Ruth-ikegah** [comment]
Hi @ibimina Not sure I understand what official links but here is a link to the website:

https://chaoss.community/

**Comment by ibimina** [comment]
@Ruth-ikegah thanks that will do
