### ISSUE TITLE
implement About Page

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#8]

**Comment by Jem256** [comment]
Hey, can this be assigned to me?

**Comment by oma131** [comment]
Hi @Jem256 Sure you can work on this issue

**Comment by Jem256** [comment]
hey @oma131 there are two About Us screens in the Figma design. Which one should I work on or they both connected?

**Comment by oma131** [comment]
Hi @Jem256, sorry for the mix-up, it is just one about page 
Check the Figma file now, the naming has been corrected.
https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=243%3A994

**Comment by mihrab34** [comment]
Hi @oma131 ,  I wanted to ask if @Jem256  is still working on this. I want to pick it up

**Comment by Jem256** [comment]
hey @mihrab34 feel free to take it on

**Comment by mihrab34** [comment]
#43 : Implemented About page

**Comment by Joshua-Ogbonna** [comment]
If this has been designed, can I work on the development?

**Comment by kaxada** [comment]
@Joshua-Ogbonna this is in development. But you can work with @mihrab34 or enhance their development via this PR https://github.com/badging/badging-website/pull/43

**Comment by mihrab34** [comment]
Hi @Joshua-Ogbonna , Perhaps you can implement the CSS for the page via this  PR #43

**Comment by Joshua-Ogbonna** [comment]
Hi @mihrab34, Okay.
