### ISSUE TITLE
[About Page] Implement page features and its reusable components

### ISSUE THREAD

**Issue by Teek-tech** [badging/eventBadging#81]
Welcome onboard....
Here's an opportunity to contribute to the "About Page" of the [Badging Website.](https://badging-website.netlify.app/)

The "About Page" is an integral part of this website and we want your work on this to align with the beautiful [prototype](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=488%3A886&t=yaPK6oov4kd7YU9u-0) we designed. Kindly ensure that your design is mobile friendly and neatly responsive to different screen sizes.

**Reusable Components** 
The following sections of the About Page must be designed independently, and imported into their respective sections:
- Motivation To Apply Section
- Submit Your Event for DEI Badge Section

You are required to inspect the UI design [here](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=2115%3A6635&t=yaPK6oov4kd7YU9u-0) and provide an updated version your work by cloning the main branch.

Your final work must look like this

![About Us](https://user-images.githubusercontent.com/19340486/220703065-c3c555a7-f675-4426-bb5d-dad55dba361a.png)

If you want this task to be assigned to you, kindly inform us via the comment section.
Thank you for your contribution!

**Comment by Holajuwon** [comment]
@Teek-tech I would like to contribute to this.

**Comment by Teek-tech** [comment]
Hello @Holajuwon 
You can jump on it. Kindly keep me posted with your progress.
Thanks.
