### ISSUE TITLE
Implement 404 page

### ISSUE THREAD

**Issue by meenarh** [badging/eventBadging#84]

**Comment by CatherineKiiru** [comment]
Hi Meenarh, is this issue taken? I'd like to work on it

**Comment by meenarh** [comment]
Hi Catherine,

It has been completed. I'll be creating a pull request soon. Please find
another issue and ask to be assigned to it.

Thanks

**Comment by meenarh** [comment]
Hi @iamkingsleey @kaxada. I'm done with this issue. I'd like you to review and merge it if there's no issues.. Thank you

**Comment by Sky-De** [comment]
Hi there
I'm sure this 404 doesn't implemented yet
So if you assign this to me
I will start creating a nice looking 404 page with minimum code

**Comment by kaxada** [comment]
@Sky-De there you go

**Comment by Sky-De** [comment]
hi there, i created 404 long time ago
why you do not merge it?
is there any problem?
let me know 
ty

**Comment by cyrilossai** [comment]
I dont know what the status of this issue , I do like to contribute
