### ISSUE TITLE
Add content to the `FAQs` in the figma file

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#9]

**Comment by DeAbby** [comment]
may i please be assigned this issue @kaxada

**Comment by Anita-ihuman** [comment]
@kaxada is this issue still available?

**Comment by kaxada** [comment]
Yes yes, it is. Can I assign it to you?

**Comment by Anita-ihuman** [comment]
@kaxada can I get a link to the Figma file here please

**Comment by kaxada** [comment]
@Anita-ihuman https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website

**Comment by Anita-ihuman** [comment]
@kaxada I drafted a few questions, can you help review  please https://docs.google.com/document/d/1hQ4IImeuyN3Y7zSgs2JI_rS6a7MFs9V1Sp0F75DTBA0/edit#

**Comment by kaxada** [comment]
@Anita-ihuman I am on it right now. @Ruth-ikegah could you find time and also fo through this doc. Just to double check

**Comment by kaxada** [comment]
This issue is related to https://github.com/badging/badging/issues/101 @Maryblessing

**Comment by Maryblessing** [comment]
> This issue is related to #101 @Maryblessing

Noted.
