### ISSUE TITLE
Navbar  doesn't match the design and the navigation links are not vertically aligned to the center

### ISSUE THREAD

**Issue by daluclemas** [badging/eventBadging#91]
![Screenshot (24)](https://user-images.githubusercontent.com/59066632/231304211-95ff254d-a890-46db-a76c-bab6b75454d7.png)

**Comment by daluclemas** [comment]
@Ruth-ikegah , i would like to work on this

**Comment by Areebah-snow** [comment]
I'd like to work on this

**Comment by daluclemas** [comment]
hi @Areebah-snow i'm already on this

**Comment by Maryblessing** [comment]
Hi @daluclemas, how is this going? Please if you're done with this issue, kindly comment so we know. If not, could you please work on completing this in a week's time so we can close this up? Thank you

**Comment by daluclemas** [comment]
> Hi @daluclemas, how is this going? Please if you're done with this issue, kindly comment so we know. If not, could you please work on completing this in a week's time so we can close this up? Thank you

hi hi @Maryblessing , i am currently on it. i was waiting for approval so that i can go ahead. thanks alot
